line-length = 100
include = ["pyproject.toml", "src/**/*.py", "tests/**/*.py"]
exclude = ['stubs']

[lint]
extend-select = [ "ALL" ]
ignore = [
  "COM812", "ISC001", "D203", "D213", "D104", "D107", "ANN401", "FIX002",
  "TD004", "TD002", "TD003", "FBT001", "ERA001", "PGH003", "RET504", "D301",
  "FAST003", "LOG015",
]

[lint.per-file-ignores]
"tests/*" = [ "S101" ]

[lint.flake8-annotations]
# https://docs.astral.sh/ruff/rules/missing-return-type-special-method/
mypy-init-return = true 
